name: "Terraform Apply"

inputs:
  INIT_CONFIG:
    required: true
    type: string
  VARIABLES_OVERRIDE:
    required: false
    type: string
    default: ""
  WORKING_DIRECTORY:
    required: false
    type: string
    default: "./terraform"

outputs:
  lambda_name:
    value: ${{ steps.output.outputs.lambda_name }}
  lambda_arn:
    value: ${{ steps.output.outputs.lambda_arn }}

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      shell: bash
      run: terraform -chdir=${{ inputs.WORKING_DIRECTORY }} init ${{ inputs.INIT_CONFIG }}

    - name: Terraform Apply
      shell: bash
      id: apply
      run: terraform -chdir=${{ inputs.WORKING_DIRECTORY }} apply -input=false ${{ inputs.VARIABLES_OVERRIDE }} -auto-approve
    
    - name: Terraform Output
      shell: bash
      id: output
      run: |
        echo "lambda_name=$(terraform -chdir=${{ inputs.WORKING_DIRECTORY }} output lambda_name)" >> $GITHUB_OUTPUT
        echo "lambda_arn=$(terraform -chdir=${{ inputs.WORKING_DIRECTORY }} output lambda_arn)" >> $GITHUB_OUTPUT
