name: "GitLint"

runs:
  using: "composite"
  steps:
  - name: Lint Commits
    uses: aschbacd/gitlint-action@v1.2.0
    with:
      re-commit-message-split: ^([^\n]*)(?:\n+([\s\S]*[^\n]))?\n*$
      re-pull-request-title: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([\w\-\.]+\))?(!)?: ((?:[\w ])+)'
      re-commit-message-subject: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([\w\-\.]+\))?(!)?: ((?:[\w ])+)'
      re-commit-message-body: '(?:\n+((?:[^#\n]+\n*?)+))??(?:\n+((?:[A-Z][a-z]+(?:-[a-z]+)*: (?:[A-Za-z]+ )+<[\w\-\.]+@(?:[\w\-]+\.)+[\w\-]{2,4}>)(?:\n+[A-Z][a-z]+(?:-[a-z]+)*: (?:[A-Za-z]+ )+<[\w\-\.]+@(?:[\w\-]+\.)+[\w\-]{2,4}>)))?(?:\n+((?:#.*\n*?)+))?\n*$'
      re-tag-name: ^v?\d+\.\d+\.\d+$
      commit-message-subject-max-length: 120
      commit-message-body-max-length: 1000
