name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      FORCE_DEPLOYMENT:
        required: false
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  BDKWorkflow:
    name: BDK Book Workflow
    uses: kognitos/bdk-book-workflow/.github/workflows/main-pipeline.yaml@main
    with:
      FORCE_DEPLOYMENT: ${{ inputs.FORCE_DEPLOYMENT || false }}
    secrets: inherit
