name: Main Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      FORCE_DEPLOYMENT:
        required: false
        type: bool
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  book-workflow:
    uses: kognitos/bdk-book-workflow/.github/workflows/main-pipeline.yml@main
