name: Setup Configuration Variables

on:
  workflow_call:
    inputs:
      CONFIG_FILE_PATH:
        required: false
        type: string
        default: "./pyproject.toml"
    outputs:
      BOOK_NAME:
        value: ${{ jobs.LoadVariables.outputs.BOOK_NAME }}
      BDK_RUNTIME_VERSION:
        value: ${{ jobs.LoadVariables.outputs.BDK_RUNTIME_VERSION }}
      AWS_ACCOUNT_ID:
        value: ${{ jobs.LoadVariables.outputs.AWS_ACCOUNT_ID }}
      AWS_REGION:
        value: ${{ jobs.LoadVariables.outputs.AWS_REGION }}
      DOCKER_REGISTRY:
        value: ${{ jobs.LoadVariables.outputs.DOCKER_REGISTRY }}
      TERRAFORM_BACKEND_BUCKET_NAME:
        value: ${{ jobs.LoadVariables.outputs.TERRAFORM_BACKEND_BUCKET_NAME }}

jobs:
  LoadVariables:
    name: Load Variables
    runs-on: ubuntu-latest
    outputs:
      BOOK_NAME: ${{ steps.vars.outputs.name }}
      BDK_RUNTIME_VERSION: ${{ steps.vars.outputs.runtime_version }}
      AWS_ACCOUNT_ID: ${{ steps.vars.outputs.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ steps.vars.outputs.AWS_REGION }}
      DOCKER_REGISTRY: ${{ steps.vars.outputs.DOCKER_REGISTRY }}
      TERRAFORM_BACKEND_BUCKET_NAME: ${{ steps.vars.outputs.TERRAFORM_BACKEND_BUCKET_NAME }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install TOML dependency
        shell: bash
        run: pip install pyyaml toml
      - name: Retrieve Variables from Configuration File
        shell: bash
        id: vars
        run: python ./.github/scripts/setup_variables.py ${{ inputs.CONFIG_FILE_PATH }}
